/**
 * Nadi Cafe - Core Configuration & Data
 */

export const config = {
    name: "Nadi Cafe",
    phone: "+251915745157",
    fallbackImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=60&w=300"
};

export const menuItems = [
    {
        id: "fallback-1",
        name: { so: "Casiir Cambe", en: "Mango Smoothie" },
        category: "Drinks",
        price: 75,
        image: "images/mango_smoothie.png",
        description: {
            so: "Casiir cambe cusub oo leh labeen iyo baraf.",
            en: "Creamy and refreshing mango smoothie made with fresh tropical mangoes."
        },
        isPopular: true,
        rating: 4.8,
        prepTime: "5-10"
    }
];

export const categories = [
    { id: "All", so: "Dhammaan", en: "All" },
    { id: "Drinks", so: "Cabitaanno", en: "Drinks" },
    { id: "Food", so: "Cunto", en: "Food" },
    { id: "Snacks", so: "Cunto Fudud", en: "Snacks" },
    { id: "Desserts", so: "Macmacaan", en: "Desserts" }
];

export const uiTranslations = {
    so: {
        heroSubtitle: "Cuno iyo Cabitaano Dhadhan Fiican leh",
        heroTitle: "Ku soo dhawaada Nadi Cafe",
        menuTab: "Menu",
        aboutTab: "Nagu Saabsan",
        popularLabel: "Caan",
        noItems: "Wax alaabo ah laguma helin qaybtan.",
        currency: "ETB",
        searchPlaceholder: "Raadi cunto ama cabitaan...",
        searchNoResults: "Wax natiijo ah laguma helin raadintaada.",
        aboutWho: "Waa Ayo Nadi Cafe?",
        aboutWhoDesc: "Nadi Cafe waa goob heer sare ah oo ku taal Jigjiga, looguna talagalay dadka jecel cuntada caafimaadka leh iyo cabitaannada dabiiciga ah.",
        aboutServe: "Maxaan Adeegnaa?",
        aboutServeDesc: "Waxaan ku takhasusnay casiirka miraha ee 100% dabiiciga ah, smoothie-yada labeenta leh, iyo Bunka Jebena ee dhaqanka ah. Sidoo kale waxaan bixinaa sambuuso iyo cuntooyin fudud oo caafimaad leh.",
        aboutStory: "Sheekadeena",
        aboutStoryDesc: "Nadi Cafe waxay ku bilaabatay aragti sahlan: in Jigjiga laga helo cunto iyo cabitaan caafimaad leh oo dhadhan fiican leh. Waxaan mar walba isticmaalnaa miro cusub oo maxali ah.",
        contactUs: "Nagala Soo Xiriir",
        location: "Goobta",
        address: "Jigjiga, wadada karamara hospital",
        phone: "Telefoon",
        whatsapp: "WhatsApp",
        addToCart: "Dalbo",
        min: "daqiiqo",
        cartTitle: "Dalabkaaga",
        total: "Wadarta Guud",
        checkout: "Dalbo",
        emptyCart: "Dalabkaagu waa maran yahay",
        back: "Dib u laabo",
        items: "alaab",
        confirmCheckout: "Ma hubaal inaad rabto inaad dalbato?",
        reviewTab: "Dib u eegis",
        searchTitle: "Raadi Menu-ga",
        rateService: "Qiimee Adeegeena",
        ratingsReviews: "Qiimeynta iyo faallooyinka",
        reviewsCount: "faallooyin",
        rateJuice: "Qiimee casiirkeena cusub",
        writeReview: "Qor faallo",
        howWasJuice: "Sidee ahaa casiirkaaga?",
        selectRating: "Dooro Qiimeynta",
        yourName: "Magacaaga",
        namePlaceholder: "t.s. Axmed Daahi",
        feedbackDetails: "Faahfaahinta Faallada",
        feedbackPlaceholder: "La wadaag khibradaada...",
        submitReview: "Gudbi Faallada",
        posted: "Waa la soo gudbiyay!",
        thanksFeedback: "Waad ku mahadsantahay la wadaagista ra'yigaaga.",
        writeAnother: "Qor mid kale",
        noReviews: "Wali ma jiraan wax faallooyin ah.",
        ratedOutOf: "Lagu qiimeeyay 5-tii",
        needsImprovement: "Wuxuu u baahan yahay horumarin",
        fair: "Dhexdhexaad",
        good: "Waqti fiican",
        veryGood: "Aad u fiican",
        excellent: "Aad iyo aad u fiican!",
        meetOurStaff: "La Kulun Shaqaalaheena",
        staffWaiters: "Adeegayaasha",
        staffCooks: "Kariiyeyaasha",
        staffHeadChef: "Maareeyaha Cuntada",
        staffBarista: "Khabiirka Bunka",
        staffWaitress: "Hogaanka Adeegayaasha"
    },
    en: {
        heroSubtitle: "From our kitchen to your heart",
        heroTitle: "Welcome to Nadi Cafe",
        menuTab: "Menu",
        aboutTab: "About Us",
        popularLabel: "Popular",
        noItems: "No items found in this category.",
        currency: "ETB",
        searchPlaceholder: "Search dishes, restaurants...",
        searchNoResults: "No results found for your search.",
        aboutWho: "Who is Nadi Cafe?",
        aboutWhoDesc: "Nadi Cafe is a premium destination in Jigjiga for health-conscious foodies and lovers of natural drinks.",
        aboutServe: "What We Serve",
        aboutServeDesc: "We specialize in 100% natural fruit juices, creamy smoothies, and authentic Ethiopian Jebena coffee. We also offer delicious sambusas and healthy light snacks.",
        aboutStory: "Our Story",
        aboutStoryDesc: "Nadi Cafe started with a simple vision: to make healthy living delicious and accessible in Jigjiga. We always use the freshest locally sourced fruits.",
        contactUs: "Contact Us",
        location: "Location",
        address: "Jigjiga, Ethiopia",
        phone: "Phone",
        whatsapp: "WhatsApp",
        addToCart: "Add to cart",
        min: "min",
        cartTitle: "Your Cart",
        total: "Grand Total",
        checkout: "Checkout",
        emptyCart: "Your cart is empty",
        back: "Back",
        items: "items",
        confirmCheckout: "Are you sure you want to checkout?",
        reviewTab: "Review",
        searchTitle: "Search Menu",
        rateService: "Rate Our Service",
        ratingsReviews: "Ratings and reviews",
        reviewsCount: "reviews",
        rateJuice: "Rate our fresh juice",
        writeReview: "Write a review",
        howWasJuice: "How was your juice?",
        selectRating: "Select Rating",
        yourName: "Your Name",
        namePlaceholder: "e.g. Ahmed Daahi",
        feedbackDetails: "Feedback Details",
        feedbackPlaceholder: "Share your experience...",
        submitReview: "Submit Review",
        posted: "Posted!",
        thanksFeedback: "Thanks for sharing your feedback.",
        writeAnother: "Write another",
        noReviews: "No reviews yet.",
        ratedOutOf: "out of 5",
        needsImprovement: "Needs Improvement",
        fair: "Fair",
        good: "Good",
        veryGood: "Very Good",
        excellent: "Excellent!",
        meetOurStaff: "Meet Our Staff",
        staffWaiters: "Waiters",
        staffCooks: "Cooks",
        staffHeadChef: "Head Chef",
        staffBarista: "Senior Barista",
        staffWaitress: "Lead Waitress"
    }
};


